include:
  - project: "sanger-pathogens/templates/ci-templates"
    ref: "improve_sed_file_substitution"
    file: "Pipelines/PaM-Info-Nextflow.gitlab-ci.yml"

# If your project contains python code, delete the sections below which disable black, isort and flake8
# See also .pre-commit-config.yaml, which will have black, isort and flake8 jobs disabled.
black:
  rules:
    - when: never

isort:
  rules:
    - when: never

flake8:
  rules:
    - when: never
#     The FARM_NAME variable can be used to set the name of the module on the farm.
#     The module name will be the same as your git project by default.

.pipeline_deploy_to_farm:
  variables:
    FARM_FILE_SED: "[main.nf]='s/nextflow +run +(.|main.nf)/${FARM_NAME}/' [nextflow.config]='s/\\{\\{${FARM_NEXTFLOW_CONFIG_VERSION_PLACEHOLDER}\\}\\}/${CI_COMMIT_REF_NAME}/' [nextflow.config]='s/\\{\\{pipeline_name\\}\\}/${FARM_NAME}/' [nextflow.config]='s/\\{\\{pipeline_url\\}\\}/${CI_PROJECT_URL}/'"
#    FARM_NAME: "put-your-chosen-module-name-here"

#     The check_scan_results job will add up the number of vulnerabilities found in each category (high, medium, etc.)
#     You can set a limit on the number of vulnerabilities that will be tolerated before the job fails; if you need
#     to do this, uncomment the section below and set the limits.  All default to zero.
#     Only set non-zero values if you are unable to fix the vulnerability.  Never do so unless you have updated all
#     dependencies to the most recent version that you can use.  If unsure, seek advice.

#check_scan_results:
#  variables:
#    CRITICAL_LIMIT: 0
#    HIGH_LIMIT: 0
#    MEDIUM_LIMIT: 0
#    LOW_LIMIT: 0
